
package com.ilient.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(	name = "SysaidApiServiceService",
					targetNamespace = "http://api.ilient.com/",
					wsdlLocation =  SysaidApiServiceService.SERVICIOLOCATION
					)
public class SysaidApiServiceService  extends Service{

	//public static final String SERVICIOLOCATION = "http://serviciossiafe.hacienda.gov.do:8080/services/SysaidApiService?wsdl";
	public static final String SERVICIOLOCATION = "http://172.16.9.36:8080/services/SysaidApiService?wsdl";

    private final static URL SYSAIDAPISERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SYSAIDAPISERVICESERVICE_EXCEPTION;
    private final static QName SYSAIDAPISERVICESERVICE_QNAME = new QName("http://api.ilient.com/", "SysaidApiServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(SERVICIOLOCATION);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYSAIDAPISERVICESERVICE_WSDL_LOCATION = url;
        SYSAIDAPISERVICESERVICE_EXCEPTION = e;
    }

    public SysaidApiServiceService() {
        super(__getWsdlLocation(), SYSAIDAPISERVICESERVICE_QNAME);
    }

    public SysaidApiServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSAIDAPISERVICESERVICE_QNAME, features);
    }

    public SysaidApiServiceService(URL wsdlLocation) {
        super(wsdlLocation, SYSAIDAPISERVICESERVICE_QNAME);
    }

    public SysaidApiServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSAIDAPISERVICESERVICE_QNAME, features);
    }

    public SysaidApiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SysaidApiServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SysaidApiService
     */
    @WebEndpoint(name = "SysaidApiServicePort")
    public SysaidApiService getSysaidApiServicePort() {
        return super.getPort(new QName("http://api.ilient.com/", "SysaidApiServicePort"), SysaidApiService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SysaidApiService
     */
    @WebEndpoint(name = "SysaidApiServicePort")
    public SysaidApiService getSysaidApiServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.ilient.com/", "SysaidApiServicePort"), SysaidApiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSAIDAPISERVICESERVICE_EXCEPTION!= null) {
            throw SYSAIDAPISERVICESERVICE_EXCEPTION;
        }
        return SYSAIDAPISERVICESERVICE_WSDL_LOCATION;
    }

}
