package rd.huma.dashboard.model.transaccional.dominio;

public enum ETipoAlertaVersion {


	CONFIGURACION_POM_AMBIENTE_MODULOS_INCOMPATIBLES,
	SCRIPT_NO_ENCONTRADO_EN_VERSION,
	SCRIPT_RESULTADO,
	VERSION_NO_SUBIO,
	VERSION_SUBIENDO
}
